### ISSUE TITLE
Ukol1

### ISSUE THREAD

**Issue by marcelahenzlova** [marcelahenzlova/Czechitas_Python#1]
@cattitude: Poslala jsem ti žádost o přidání do repozitáře a uložila jsem tam úkol 1, - mrkneš, prosím? :-) Díky.

**Comment by cattitude** [comment]
@marcelahenzlova Ahoj, potvrzuji, že úkol vidím. Pokusím se co nejdřív opravit a dám vědět.:)

**Comment by cattitude** [comment]
@marcelahenzlova
Ahoj, díval jsem se řešení tvého úkolu a mám k tomu pár poznámek:

- Myslím, že objektově orientované programování jsi pochopila, použití tříd a dědičností máš správné.:)
- Podívej se, jak se v Pythonu používají pravdivostní hodnoty - datový typ bool (boolean). V úkolu řešíš rozlišení komerční budovy pomocí stringu, což není ideální. **Toto bych opravdu poprosil opravit.:)**

Oceňuji, že ses pustila do všech bonusů, to je opravdu super! Měl bych k nim taky pár poznámek, a to spíše k zamyšlení, ke splnění úkolu je řešit nemusíš:

- Šlo by nějak v metodě __str__ vypisovat český název typu pozemku? Nešlo by to třeba i s využitím vytvořené Enum třídy? 
- Šla by abstraktní třída Property doplnit ještě o nějakou abstraktní metodu, kterou máme u obou tříd Estate i Residence?:)
- Enum třída byla ještě ke všemu samostudium, takže znovu oceňuji, žes ji implementovala. Zkus při vytváření objektu pozemek využít rovnou Estate_types.land místo stringu "land". Ve třídě Estate pak k hodnotě koeficientu můžeš přistoupit rovnou přes self.estate_type.value.
- TaxReport je pak úplně perfektní, líbí se mi i kontrola Property. :) 

Celkově super, moje komentáře jsou ve většině pouze náměty, jak ten úkol posunout ještě o kousek dál. Prosím jen o opravení stringu na bool u commerical. Pak udělej klasicky nový commit a pushni ho sem na GitHub. Jakmile to budeš mít, hoď mi tady opět komentář.

Děkuju a užij si víkend:)
Adam

**Comment by marcelahenzlova** [comment]
@cattitude: Ahoj, opravila jsem na boolean a stydím se :-D

Co se týče bonusů - napadlo mě, že to Enum použiju jako slovník mezi anglickým a českým překladem typu pozemku, ale pak mi přišlo lepší ho použít na ty koeficienty a i tak mi trochu trvalo přijít na správnou syntax, aby mi to vypisovalo to, co potřebuji :-D Takže budu určitě ráda, když uvidím nějaké finální řešení i těch bonusů. Bude to pak na Discordu? Díky, Marcela

**Comment by cattitude** [comment]
@marcelahenzlova 
Super, díky za rychlou opravu. Není se za co stydět, vlastně to byla maličkost. Výhoda použití boolean je třeba v tom, že pak stačí napsat jen "if self.commercial: ...". :)

Úkol máš tedy hotový.:) Co se týče finálního řešení, ještě se domluvím s lektorem a ostatními koučkami/kouči, jak to přesně uděláme.
